// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiXDH4bOgjp6_9gQz9dJzsnJOhDsRRRfQ',
    appId: '1:714791806905:android:68f8e503125cf837e6f868',
    messagingSenderId: '714791806905',
    projectId: 'trip-planer-6ef82',
    databaseURL: 'https://trip-planer-6ef82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trip-planer-6ef82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv14H4mBOks6tHZCR6JAXXm78xMi-b9NE',
    appId: '1:714791806905:ios:54cb3ed19e6bcb5be6f868',
    messagingSenderId: '714791806905',
    projectId: 'trip-planer-6ef82',
    databaseURL: 'https://trip-planer-6ef82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trip-planer-6ef82.firebasestorage.app',
    iosClientId: '714791806905-f5q2kjavv3qdban1t07djnudcak61tk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelPlaner',
  );
}
